import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
    Box,
    Button,
    Dialog,
    DialogActions,
    DialogContent,
    DialogTitle,
    MenuItem,
    Paper,
    Snackbar,
    Stack,
    Chip,
    TextField,
    Typography
} from "@mui/material";
import { DataGrid } from "@mui/x-data-grid";
import MainLayout from "../layouts/MainLayout";
import {
    createAuditLog,
    assignFraudCaseAnalyst,
    getAllFraudCases,
    updateFraudCaseStatus,
    getInvestigationSummary
} from "../services/analyticsService";
import { exportToCsvWithAudit } from "../utils/exportCsv";
import { filterByDateRange } from "../utils/dateFilters";
import { getCaseRiskScore, getCaseSla } from "../utils/caseSla";

export default function Investigations({ darkMode, setDarkMode, dateRange, setDateRange }) {
    const navigate = useNavigate();
    const [searchParams] = useSearchParams();
    const [cases, setCases] = useState([]);
    const [searchTerm, setSearchTerm] = useState("");
    const [statusFilter, setStatusFilter] = useState(searchParams.get("status") || "ALL");
    const [summaryDialogOpen, setSummaryDialogOpen] = useState(false);
    const [selectedSummary, setSelectedSummary] = useState(null);
    const [selectedIds, setSelectedIds] = useState([]);
    const [assignmentDialogOpen, setAssignmentDialogOpen] = useState(false);
    const [assignmentCaseIds, setAssignmentCaseIds] = useState([]);
    const [assignmentAnalyst, setAssignmentAnalyst] = useState(localStorage.getItem("fullName") || "Balaji");
    const [assignmentReason, setAssignmentReason] = useState("");
    const [assignmentError, setAssignmentError] = useState("");
    const [snackbarOpen, setSnackbarOpen] = useState(false);

    const loadCases = async () => {
        const data = await getAllFraudCases();
        setCases(Array.isArray(data) ? data : []);
    };

    useEffect(() => {
        loadCases();
    }, []);

    useEffect(() => {
        setStatusFilter(searchParams.get("status") || "ALL");
    }, [searchParams]);

    const filteredCases = filterByDateRange(cases, dateRange).filter((item) => {
        const sla = getCaseSla(item);
        const matchesSearch = `${item.caseNumber} ${item.status} ${item.assignedAnalyst} ${item.notes}`
            .toLowerCase()
            .includes(searchTerm.toLowerCase());
        const matchesStatus =
            statusFilter === "ALL" ||
            item.status === statusFilter ||
            (statusFilter === "OVERDUE" && sla.label === "Overdue") ||
            (statusFilter === "CRITICAL" && getCaseRiskScore(item) >= 100);

        return matchesSearch && matchesStatus;
    });

    const showSummary = async (caseId) => {
        const data = await getInvestigationSummary(caseId);
        setSelectedSummary(data);
        setSummaryDialogOpen(true);
        await createAuditLog("Generated investigation summary", "FraudCase", caseId);
    };

    const exportCasePdf = (item) => {
        const doc = new jsPDF();

        doc.setFontSize(18);
        doc.text("Fraud Investigation Report", 14, 20);

        doc.setFontSize(11);
        doc.text(`Case Number: ${item.caseNumber}`, 14, 32);
        doc.text(`Status: ${item.status}`, 14, 40);
        doc.text(`Assigned Analyst: ${item.assignedAnalyst || "Unassigned"}`, 14, 48);
        doc.text(`Risk Score: ${item.riskScore || "N/A"}`, 14, 56);

        autoTable(doc, {
            startY: 68,
            head: [["Field", "Details"]],
            body: [
                ["Case Notes", item.notes || "N/A"],
                ["Recommended Action", "Review transaction history, verify customer identity, and document the final decision."],
                ["Generated By", "FraudOps Platform"]
            ],
        });

        doc.save(`${item.caseNumber}-report.pdf`);
        createAuditLog("Exported investigation PDF", "FraudCase", item.id);
    };

    const getSelectionIds = (selectionModel) => {
        if (Array.isArray(selectionModel)) return selectionModel;
        if (selectionModel?.ids) return Array.from(selectionModel.ids);
        return [];
    };

    const openAssignmentDialog = (caseIds) => {
        setAssignmentCaseIds(caseIds);
        setAssignmentAnalyst(localStorage.getItem("fullName") || "Balaji");
        setAssignmentReason("");
        setAssignmentError("");
        setAssignmentDialogOpen(true);
    };

    const submitAssignment = async () => {
        if (!assignmentReason.trim()) {
            setAssignmentError("Assignment reason is required.");
            return;
        }

        await Promise.all(
            assignmentCaseIds.map(async (caseId) => {
                await assignFraudCaseAnalyst(caseId, assignmentAnalyst);
                await createAuditLog(
                    `Assigned case to ${assignmentAnalyst}: ${assignmentReason.trim()}`,
                    "FraudCase",
                    caseId
                );
            })
        );

        setAssignmentDialogOpen(false);
        setSelectedIds([]);
        setSnackbarOpen(true);
        await loadCases();
    };

    const bulkEscalate = async () => {
        await Promise.all(
            selectedIds.map(async (caseId) => {
                await updateFraudCaseStatus(caseId, "ESCALATED");
                await createAuditLog("Bulk escalated fraud case", "FraudCase", caseId);
            })
        );
        setSelectedIds([]);
        setSnackbarOpen(true);
        await loadCases();
    };

    const selectedRows = filteredCases.filter((item) => selectedIds.includes(item.id));

    return (
        <MainLayout
            darkMode={darkMode}
            setDarkMode={setDarkMode}
            searchTerm={searchTerm}
            setSearchTerm={setSearchTerm}
            dateRange={dateRange}
            setDateRange={setDateRange}
            onRefresh={loadCases}
        >
            <Stack direction="row" justifyContent="space-between" alignItems="center" mb={3}>
                <Box>
                    <Typography variant="h4" fontWeight={800}>
                        Investigations
                    </Typography>
                    <Typography color="text.secondary">
                        Manage fraud cases, status updates, and AI investigation summaries.
                    </Typography>
                </Box>

                <Stack direction="row" spacing={1}>
                    {selectedIds.length > 0 && (
                        <>
                            <Button
                                variant="outlined"
                                color="warning"
                                onClick={bulkEscalate}
                            >
                                Escalate Selected ({selectedIds.length})
                            </Button>

                            <Button
                                variant="outlined"
                                onClick={() => openAssignmentDialog(selectedIds)}
                            >
                                Assign Selected
                            </Button>
                        </>
                    )}

                    <Button
                        variant="outlined"
                        onClick={() => exportToCsvWithAudit(
                            "investigations.csv",
                            selectedRows.length > 0 ? selectedRows : filteredCases,
                            createAuditLog,
                            "FraudCase",
                            0
                        )}
                    >
                        Export {selectedRows.length > 0 ? "Selected" : "CSV"}
                    </Button>

                    <Button variant="contained" onClick={loadCases}>
                        Refresh
                    </Button>
                </Stack>
            </Stack>

            <Paper sx={{ p: 2, mb: 3, borderRadius: 3 }}>
                <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>
                    <Chip label="All Cases" onClick={() => setStatusFilter("ALL")} color={statusFilter === "ALL" ? "primary" : "default"} clickable />
                    <Chip label="Escalated" onClick={() => setStatusFilter("ESCALATED")} color={statusFilter === "ESCALATED" ? "warning" : "default"} clickable />
                    <Chip label="Closed" onClick={() => setStatusFilter("CLOSED")} color={statusFilter === "CLOSED" ? "success" : "default"} clickable />
                    <Chip label="Critical Risk" onClick={() => setStatusFilter("CRITICAL")} color={statusFilter === "CRITICAL" ? "error" : "default"} clickable />
                    <Chip label="Overdue SLA" onClick={() => setStatusFilter("OVERDUE")} color={statusFilter === "OVERDUE" ? "error" : "default"} clickable />
                </Stack>
            </Paper>

            <Paper sx={{ height: 560, borderRadius: 3 }}>
                <DataGrid
                    rows={filteredCases}
                    columns={[
                        { field: "caseNumber", headerName: "Case", width: 140 },
                        { field: "status", headerName: "Status", width: 160 },
                        { field: "assignedAnalyst", headerName: "Analyst", width: 190 },
                        { field: "riskScore", headerName: "Risk Score", width: 130 },
                        {
                            field: "sla",
                            headerName: "SLA",
                            width: 170,
                            renderCell: (params) => {
                                const sla = getCaseSla(params.row);
                                return <Chip label={`${sla.label} · ${sla.detail}`} color={sla.color} size="small" />;
                            }
                        },
                        { field: "notes", headerName: "Notes", flex: 1 },
                        {
                            field: "actions",
                            headerName: "Actions",
                            width: 430,
                            sortable: false,
                            renderCell: (params) => (
                                <Stack direction="row" spacing={1}>
                                    <Button
                                        size="small"
                                        variant="outlined"
                                        onClick={async () => {
                                            await updateFraudCaseStatus(params.row.id, "UNDER_REVIEW");
                                            await createAuditLog("Started fraud case review", "FraudCase", params.row.id);
                                            await loadCases();
                                        }}
                                    >
                                        Review
                                    </Button>

                                    <Button
                                        size="small"
                                        variant="outlined"
                                        onClick={async () => {
                                            await updateFraudCaseStatus(params.row.id, "ESCALATED");
                                            await createAuditLog("Escalated fraud case", "FraudCase", params.row.id);
                                            await loadCases();
                                        }}
                                    >
                                        Escalate
                                    </Button>

                                    <Button
                                        size="small"
                                        variant="outlined"
                                        onClick={() => openAssignmentDialog([params.row.id])}
                                    >
                                        Assign
                                    </Button>

                                    <Button
                                        size="small"
                                        variant="contained"
                                        onClick={() => showSummary(params.row.id)}
                                    >
                                        AI Summary
                                    </Button>

                                    <Button
                                        size="small"
                                        color="secondary"
                                        variant="contained"
                                        onClick={() => navigate(`/cases/${params.row.id}`)}
                                    >
                                        Open
                                    </Button>
                                </Stack>
                            )
                        }
                    ]}
                    pageSizeOptions={[5, 10, 25]}
                    initialState={{
                        pagination: {
                            paginationModel: { pageSize: 10, page: 0 },
                        },
                    }}
                    showToolbar
                    checkboxSelection
                    rowSelectionModel={{ type: "include", ids: new Set(selectedIds) }}
                    onRowSelectionModelChange={(newSelection) => setSelectedIds(getSelectionIds(newSelection))}
                    slotProps={{
                        toolbar: {
                            showQuickFilter: true,
                            quickFilterProps: { debounceMs: 400 }
                        }
                    }}
                    disableRowSelectionOnClick
                />
            </Paper>

            <Dialog
                open={summaryDialogOpen}
                onClose={() => setSummaryDialogOpen(false)}
                maxWidth="md"
                fullWidth
            >
                <DialogTitle>AI Investigation Summary</DialogTitle>

                <DialogContent>
                    {selectedSummary && (
                        <>
                            <Typography fontWeight={800} mb={1}>
                                Summary
                            </Typography>
                            <Typography mb={3}>
                                {selectedSummary.summary}
                            </Typography>

                            <Typography fontWeight={800} mb={1}>
                                Recommended Next Steps
                            </Typography>
                            <Typography>
                                {selectedSummary.recommendedNextSteps}
                            </Typography>
                        </>
                    )}
                </DialogContent>

                <DialogActions>
                    <Button onClick={() => setSummaryDialogOpen(false)}>
                        Close
                    </Button>
                </DialogActions>
            </Dialog>

            <Dialog
                open={assignmentDialogOpen}
                onClose={() => setAssignmentDialogOpen(false)}
                maxWidth="sm"
                fullWidth
            >
                <DialogTitle>
                    Assign {assignmentCaseIds.length} Case{assignmentCaseIds.length === 1 ? "" : "s"}
                </DialogTitle>

                <DialogContent>
                    <Stack spacing={2} mt={1}>
                        <TextField
                            select
                            label="Analyst"
                            value={assignmentAnalyst}
                            onChange={(event) => setAssignmentAnalyst(event.target.value)}
                            fullWidth
                        >
                            <MenuItem value="Balaji">Balaji</MenuItem>
                            <MenuItem value="Senior Investigator">Senior Investigator</MenuItem>
                            <MenuItem value={localStorage.getItem("fullName") || "Balaji"}>
                                {localStorage.getItem("fullName") || "Balaji"}
                            </MenuItem>
                        </TextField>

                        <TextField
                            label="Assignment Reason"
                            value={assignmentReason}
                            onChange={(event) => {
                                setAssignmentReason(event.target.value);
                                setAssignmentError("");
                            }}
                            error={Boolean(assignmentError)}
                            helperText={assignmentError}
                            multiline
                            minRows={3}
                            fullWidth
                        />
                    </Stack>
                </DialogContent>

                <DialogActions>
                    <Button onClick={() => setAssignmentDialogOpen(false)}>
                        Cancel
                    </Button>
                    <Button variant="contained" onClick={submitAssignment}>
                        Save Assignment
                    </Button>
                </DialogActions>
            </Dialog>

            <Snackbar
                open={snackbarOpen}
                autoHideDuration={3000}
                onClose={() => setSnackbarOpen(false)}
                message="Investigation updates saved"
            />
        </MainLayout>
    );
}
